openapi: 3.0.2
info:
    title: Booking Platform API
    version: '1.0'
paths:
    /user/login:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestDto'
            tags:
                - bookingPlatform
            parameters:
                -
                    name: x-matrix-source
                    schema:
                        type: string
                        example: WEB
                    in: header
                    required: true
                -
                    name: x-time-zone
                    schema:
                        type: string
                        example: Europe/Madrid
                    in: header
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseDto'
                                properties:
                                    token:
                                        description: Authentication token
                                        type: string
                    description: Successful login
                '401':
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        description: Error message
                                        type: string
                    description: Unauthorized
            operationId: login
            summary: User login
    /user/current/bookings:
        get:
            tags:
                - bookingPlatform
            parameters:
                -
                    style: form
                    explode: true
                    name: include
                    description: Specifies which related resources should be included in the response
                    schema:
                        type: array
                        items:
                            enum:
                                - locations
                                - bookingSettings
                            type: string
                    in: query
                    required: false
                -
                    name: x-matrix-source
                    schema:
                        type: string
                        example: WEB
                    in: header
                    required: true
                -
                    name: x-time-zone
                    schema:
                        type: string
                        example: Europe/Madrid
                    in: header
                    required: true
                -
                    name: cookie
                    description: ''
                    schema:
                        type: string
                    in: header
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserBookingResponseDto'
                    description: List of current user bookings
                '401':
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        description: Error message
                                        type: string
                    description: Unauthorized
            operationId: getUserBookings
            summary: Retrieve current user bookings
    /booking:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/BookingRequestDto'
                required: true
            tags:
                - bookingPlatform
            parameters:
                -
                    name: x-matrix-source
                    schema:
                        type: string
                        example: WEB
                    in: header
                    required: true
                -
                    name: x-time-zone
                    schema:
                        type: string
                        example: Europe/Madrid
                    in: header
                    required: true
                -
                    name: cookie
                    description: ''
                    schema:
                        type: string
                    in: header
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BookingsResponseDto'
                    description: OK
                '409':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BookingErrorResponse'
                    description: NO OK
            operationId: book
    /availability:
        get:
            tags:
                - bookingPlatform
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AvailabilityResponseDto'
                    description: OK
            operationId: getAvailability
        parameters:
            -
                name: f
                description: ''
                schema:
                    type: string
                in: query
                required: true
            -
                name: t
                description: ''
                schema:
                    type: string
                in: query
                required: true
            -
                name: bc
                description: ''
                schema:
                    type: string
                in: query
                required: true
            -
                name: l
                description: ''
                schema:
                    type: string
                in: query
                required: true
            -
                name: include
                description: ''
                schema:
                    type: array
                    items:
                        type: string
                in: query
                required: true
            -
                name: status
                description: ''
                schema:
                    type: array
                    items:
                        type: string
                in: query
                required: true
            -
                name: x-matrix-source
                schema:
                    type: string
                    example: WEB
                in: header
                required: true
            -
                name: x-time-zone
                schema:
                    type: string
                    example: Europe/Madrid
                in: header
                required: true
            -
                name: cookie
                description: ''
                schema:
                    type: string
                in: header
                required: true
components:
    schemas:
        LoginRequestDto:
            required:
                - username
                - password
            type: object
            properties:
                username:
                    type: string
                    example: fakeMail
                password:
                    type: string
                    example: fakePassword
        AncestorLocationDto:
            title: Root Type for AncestorLocationDto
            description: ''
            type: object
            properties:
                id:
                    type: string
                organisationId:
                    format: int32
                    type: integer
                kind:
                    type: string
                name:
                    type: string
                qualifiedName:
                    type: string
                left:
                    format: int32
                    type: integer
                right:
                    format: int32
                    type: integer
                isFlex:
                    type: boolean
                settings:
                    $ref: '#/components/schemas/SettingDto'
                    properties:
                        timeZone:
                            type: object
                            properties:
                                location:
                                    type: object
                                    properties:
                                        id:
                                            format: int32
                                            type: integer
                                        name:
                                            type: string
                                zoneId:
                                    type: string
            example:
                id: 554228294
                organisationId: 555510196
                kind: BUILDING
                name: Company Parking
                qualifiedName: Company Parking
                left: 1286
                right: 1741
                isFlex: false
                settings:
                    timeZone:
                        location:
                            id: 554228294
                            name: Company Parking
                        zoneId: Europe/Madrid
        SettingDto:
            title: Root Type for SettingDto
            description: ''
            type: object
            properties:
                timeZone:
                    $ref: '#/components/schemas/TimeZoneDto'
                    properties:
                        location:
                            type: object
                            properties:
                                id:
                                    format: int32
                                    type: integer
                                name:
                                    type: string
                        zoneId:
                            type: string
            example:
                timeZone:
                    location:
                        id: 554228294
                        name: Company Parking
                    zoneId: Europe/Madrid
        TimeZoneDto:
            title: Root Type for TimeZoneDto
            description: ''
            type: object
            properties:
                location:
                    $ref: '#/components/schemas/TimeZoneLocationDto'
                    properties:
                        id:
                            format: int32
                            type: integer
                        name:
                            type: string
                zoneId:
                    type: string
            example:
                location:
                    id: 554228294
                    name: Company Parking
                zoneId: Europe/Madrid
        BookingDto:
            title: Root Type for BookingDto
            description: ''
            type: object
            properties:
                id:
                    type: string
                owner:
                    $ref: '#/components/schemas/IdentityDto'
                    properties:
                        id:
                            format: int32
                            type: integer
                        name:
                            type: string
                        email:
                            type: string
                bookedBy:
                    $ref: '#/components/schemas/IdentityDto'
                    properties:
                        id:
                            format: int32
                            type: integer
                        name:
                            type: string
                        email:
                            type: string
                timeFrom:
                    format: date-time
                    type: string
                timeTo:
                    format: date-time
                    type: string
                locationId:
                    type: string
            example:
                id: 9991132992
                owner:
                    id: 990061102
                    name: Alex Johnson
                    email: alexjohnson@example.com
                bookedBy:
                    id: 990061103
                    name: Alex Johnson
                    email: alexjohnson@example.com
                timeFrom: '2024-03-19T08:00:00.000'
                timeTo: '2024-03-19T19:00:00.000'
                locationId: 555220406
        IdentityDto:
            title: Root Type for IdentityDto
            description: ''
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
                email:
                    type: string
            example:
                id: 990061102
                name: Alex Johnson
                email: alexjohnson@example.com
        TimeZoneLocationDto:
            title: Root Type for LocationDto
            description: ''
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
            example:
                id: 554228294
                name: Company Parking
        LocationDto:
            title: Root Type for LocationDto
            description: ''
            type: object
            properties:
                id:
                    type: string
                organisationId:
                    type: string
                parentId:
                    type: string
                name:
                    type: string
                shortQualifier:
                    type: string
                longQualifier:
                    type: string
                qualifiedName:
                    type: string
                bookingCategoryId:
                    type: string
                settings:
                    $ref: '#/components/schemas/SettingDto'
                    properties:
                        timeZone:
                            type: object
                            properties:
                                location:
                                    type: object
                                    properties:
                                        id:
                                            format: int32
                                            type: integer
                                        name:
                                            type: string
                                zoneId:
                                    type: string
            example:
                id: 555220406
                organisationId: 555510196
                parentId: 554228368
                name: 94 Exterior Space
                shortQualifier: Company Parking
                longQualifier: 'Company Office Parking, Company Parking'
                qualifiedName: '94 Exterior Space, Company Office Parking, Company Parking'
                bookingCategoryId: 554240906
                settings:
                    timeZone:
                        location:
                            id: 554228294
                            name: Company Parking
                        zoneId: Europe/Madrid
        BookingsResponseDto:
            title: Root Type for BookingsResponseDto
            description: ''
            type: object
            properties:
                id:
                    type: string
                owner:
                    $ref: '#/components/schemas/IdentityDto'
                    properties:
                        id:
                            format: int32
                            type: integer
                        name:
                            type: string
                        email:
                            type: string
                bookedBy:
                    $ref: '#/components/schemas/IdentityDto'
                    properties:
                        id:
                            format: int32
                            type: integer
                        name:
                            type: string
                        email:
                            type: string
                timeFrom:
                    format: date-time
                    type: string
                timeTo:
                    format: date-time
                    type: string
                locationId:
                    type: string
                locationKind:
                    type: string
                status:
                    type: string
                hasStarted:
                    type: boolean
                hasEnded:
                    type: boolean
                duration:
                    type: object
                    properties:
                        millis:
                            format: int32
                            type: integer
                possibleActions:
                    type: object
                    properties:
                        edit:
                            type: boolean
                        cancel:
                            type: boolean
                        approve:
                            type: boolean
                        confirm:
                            type: boolean
                        endEarly:
                            type: boolean
                        changeOwner:
                            type: boolean
                        start:
                            type: boolean
                        viewHistory:
                            type: boolean
                checkInStatus:
                    type: string
                attendeeCount:
                    format: int32
                    type: integer
                ownerIsAttendee:
                    type: boolean
                source:
                    type: string
                version:
                    type: string
                hasExternalNotes:
                    type: boolean
            example:
                id: 29523577
                owner:
                    id: 6346342
                    name: fakeUser
                    email: fakeMail
                bookedBy:
                    id: 56346334
                    name: fakeUser
                    email: fakeMail
                timeFrom: '2024-05-23T08:00:00.000'
                timeTo: '2024-05-23T19:00:00.000'
                locationId: 6435631
                locationKind: EQUIPMENT
                status: CONFIRMED
                hasStarted: false
                hasEnded: false
                duration:
                    millis: 325325
                possibleActions:
                    edit: true
                    cancel: true
                    approve: false
                    confirm: false
                    endEarly: false
                    changeOwner: false
                    start: false
                    viewHistory: true
                checkInStatus: NOT_REQUIRED
                attendeeCount: 1
                ownerIsAttendee: true
                source: WEB
                version: 1
                hasExternalNotes: false
        UserBookingResponseDto:
            title: Root Type for BookingResponseDto
            description: ''
            required:
                - locations
                - bookings
                - ancestorLocations
            type: object
            properties:
                bookings:
                    type: array
                    items:
                        $ref: '#/components/schemas/BookingDto'
                locations:
                    type: array
                    items:
                        $ref: '#/components/schemas/LocationDto'
                ancestorLocations:
                    type: array
                    items:
                        $ref: '#/components/schemas/AncestorLocationDto'
            example:
                bookings:
                    -
                        id: 9991132992
                        owner:
                            id: 990061102
                            name: Alex Johnson
                            email: alexjohnson@example.com
                        bookedBy:
                            id: 990061103
                            name: Alex Johnson
                            email: alexjohnson@example.com
                        timeFrom: '2024-03-19T08:00:00.000'
                        timeTo: '2024-03-19T19:00:00.000'
                        locationId: 555220406
                locations:
                    -
                        id: 555220406
                        organisationId: 555510196
                        parentId: 554228368
                        name: 34 Exterior Space
                        shortQualifier: Company Parking
                        longQualifier: 'Company Office Parking, Company Parking'
                        qualifiedName: '34 Exterior Space, Company Office Parking, Company Parking'
                        bookingCategoryId: 554240906
                        settings:
                            timeZone:
                                location:
                                    id: 554228294
                                    name: Company Parking
                                zoneId: Europe/Madrid
                ancestorLocations:
                    -
                        id: 554228294
                        organisationId: 555510196
                        kind: BUILDING
                        name: Company Parking
                        qualifiedName: Company Parking
                        left: 1286
                        right: 1741
                        isFlex: false
                        settings:
                            timeZone:
                                location:
                                    id: 554228294
                                    name: Company Parking
                                zoneId: Europe/Madrid
        AvailabilityResponseDto:
            title: Root Type for AvailabilityResponseDto
            description: ''
            type: object
            properties:
                discreteAvailability:
                    type: array
                    items:
                        $ref: '#/components/schemas/AvailabilityDiscreteDto'
                locations:
                    type: array
                    items:
                        $ref: '#/components/schemas/AvailabilityLocationDto'
                ancestorLocations:
                    description: ''
                    type: array
                    items:
                        $ref: '#/components/schemas/AncestorLocationDto'
            example:
                locations:
                    -
                        id: xxxx
                        name: '3423'
                        longQualifier: parking
                discreteAvailability:
                    -
                        locationId: '1233452'
                        status: a34234
        AvailabilityLocationDto:
            title: Root Type for AvailabilityLocationDto
            description: ''
            required:
                - parentId
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
                longQualifier:
                    type: string
                parentId:
                    description: ''
                    type: string
            example:
                id: xxxx
                name: '3423'
                longQualifier: parking
        AvailabilityDiscreteDto:
            title: Root Type for AvailabilityDiscreteDto
            description: ''
            type: object
            properties:
                locationId:
                    type: string
                status:
                    enum:
                        - AVAILABLE
                        - BOOKED
                        - UNAVAILABLE
                    type: string
            example:
                locationId: '1233452'
                status: a34234
        BookingRequestDto:
            title: Root Type for BookingRequestDto
            description: ''
            required:
                - owner
                - bookingGroup
            type: object
            properties:
                timeFrom:
                    type: string
                timeTo:
                    type: string
                locationId:
                    type: string
                attendees:
                    type: array
                    items: {}
                extraRequests:
                    type: array
                    items: {}
                bookingGroup:
                    $ref: '#/components/schemas/BookingGroupDto'
                    properties:
                        repeatEndDate:
                            format: date
                            type: string
                owner:
                    $ref: '#/components/schemas/IdentityDto'
                    properties:
                        id:
                            format: int32
                            type: integer
                        email:
                            type: string
                        name:
                            type: string
                ownerIsAttendee:
                    type: boolean
                source:
                    type: string
            example:
                timeFrom: '2024-05-28T08:00:00.000'
                timeTo: '2024-05-28T19:00:00.000'
                locationId: 2523523
                attendees: []
                extraRequests: []
                bookingGroup:
                    repeatEndDate: '2024-05-14'
                owner:
                    id: 23523523
                    email: fakeMail
                    name: fakeUser
                ownerIsAttendee: true
                source: WEB
        BookingGroupDto:
            title: Root Type for BookingGroupDto
            description: ''
            type: object
            properties:
                repeatEndDate:
                    type: string
            example:
                repeatEndDate: '2024-05-14'
        LoginResponseDto:
            title: Root Type for LoginResponseDto
            description: ''
            type: object
            properties:
                organisationId:
                    type: string
                personId:
                    type: string
                name:
                    type: string
                email:
                    type: string
            example:
                organisationId: 532523
                personId: 23532523
                name: fakeName
                email: fakeMail
        BookingErrorResponse:
            title: Root Type for BookingErrorResponse
            description: ''
            type: object
            properties:
                messageCode:
                    type: string
                message:
                    type: string
            example:
                messageCode: fasfasf23
                message: aasdasfas2
    securitySchemes:
        ApiKeyAuth:
            type: apiKey
            name: x-matrix-source
            in: header
security:
    -
        ApiKeyAuth: []
